Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.InventoryFindFunction
      CodeUri: /Users/sjagmeet37/IdeaProjects/SacAws/HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64